### ISSUE TITLE
Значения температур

### ISSUE THREAD

**Issue by aeg87** [MihVS/zont_ha#19]
Доброго дня!
Не ишью. а скорее пожелания:
1. Значения температур ТН и ГВС округлять до одной или двух цифр после десятичной точки. Значение вида "43,59765625 °C", мне кажется, излишне точным;
2. Я так понимаю, в API есть глюк. Когда датчик температуры недоступен (по крайней мере, беспроводной), например, электричество кончилось – отдаётся значение в несколько тысяч градусов, что портит всю статистику. 
На графике это выглядит так:
![image](https://github.com/MihVS/zont_ha/assets/56793623/b7bee80c-3a0f-4675-8012-49102af48236)

Я решал это таким костылём
```
    zont_bedroom_temp:
      value_template: '{% if states.sensor.zont_new.attributes.devices[0].sensors[3].value > 100 %} 23 {% else %} {{states.sensor.zont_new.attributes.devices[0].sensors[3].value}} {% endif %}'
      friendly_name: 'Температура в спальне'
      unit_of_measurement: '°C'
```
